// src/client/pages/FamilyGroup.jsx
import React from 'react';
import PropTypes from 'prop-types';
import Helmet from 'react-helmet';

import withTitle from '../hoc/withTitle';
import TitleBanner from '../components/TitleBanner';

import customStyles from './FamilyGroup.css';

const FamilyGroupRow = props => (
  <div className={customStyles.tableRow}>
    <div className={customStyles.rowTitle}>
      {props.title}
    </div>
    <div className={customStyles.rowDays}>
      {props.days}
    </div>
    <div className={customStyles.rowDescription}>
      {props.description}
    </div>
    <div className={customStyles.rowSignup}>
      <a href={props.signupLink}>Sign Up &gt;</a>
    </div>
  </div>
);

FamilyGroupRow.propTypes = {
  title: PropTypes.string.isRequired,
  days: PropTypes.string.isRequired,
  description: PropTypes.string.isRequired,
  signupLink: PropTypes.string.isRequired,
};

const FamilyGroup = () => (
  <div>
    <Helmet>
      <link rel="stylesheet" type="text/css" href="/public/assets/pages/FamilyGroup.bundle.css" />
    </Helmet>

    <TitleBanner src="/static/images/familygroup/fg_background.jpg">
      Family Groups
    </TitleBanner>

    <div className={customStyles.pageContent}>
      <div className="description">
        {'At GCC we place a high emphasis on Family Groups because we believe that it is in these smaller settings that we are able to meet with God, building meaningful relationships, and develop biblical accountability. Family groups meet on a weekly basis at various places.'}
        <br />
        <br />
        {'Through Bible study, discussions, sharing and prayer, we learn to live out the teachings of the Bible in our daily lives. You are strongly encouraged to join a family group that fits your needs,interests and life situation.'}
        <br />
        <br />
        {'Family groups are divided between the Harvest (undergraduate), Crossroad (post-college), and International groups.'}
        <br />
        <br />
        {'Please watch the video below to learn more!'}
      </div>

      <iframe
        className={customStyles.video}
        src="https://www.youtube.com/embed/rvXubANV7RA"
        frameBorder="0"
        title="intro"
        allow="autoplay; encrypted-media"
        allowFullScreen
      />

      <div className={customStyles.signupTable}>
        <FamilyGroupRow
          title="College"
          days="Mondays to Thursdays"
          description="Our College Family Groups meet once a week on Drexel, Moore, Penn, Temple, and USciences!"
          signupLink="#"
        />
        <FamilyGroupRow
          title="Young Adults"
          days="Mondays to Thursdays"
          description="Our Young Adult Family Groups have a mix of post-undergraduate, grad students, PhD's, working adults, and young married couples."
          signupLink="#"
        />
        <FamilyGroupRow
          title="International"
          days="Thursdays"
          description="Description needed"
          signupLink="#"
        />
      </div>
    </div>
  </div>
);

const FamilyGroupPage = withTitle('Family Group')(FamilyGroup);

export default FamilyGroupPage;

// client2/app/familygroup/familygroup/familygroup.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'familygroup',
  templateUrl: './familygroup.component.html',
  styleUrls: ['./familygroup.component.css']
})
export class FamilygroupComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="jumbotronMini familygroup">
  <h1>Family Groups</h1>
</div>

<div class="fgBackground">
  <div class="container fg">
    <div class="row fgInfo">
      <p>At GCC, we place a high emphasis on Family Groups because we believe that
        it is in these smaller settings that we are able to meet with God, building
        meaningful relationships, and develop biblical accountability. Family
        groups meet on a weekly basis at various places.</p>

      <p>Through Bible study, discussions, sharing and prayer, we learn to live
        out the teachings of the Bible in our daily lives. You are strongly
        encouraged to join a family group that fits your needs, interests and
        life situation.</p>

      <p>Family groups are divided between the Harvest (undergraduate), Crossroad
        (post-college), and International groups. Please watch the video below to learn more!</p>
    </div>
  </div>
</div>

<div class="fgBackground2">
  <div class="container fg" id="fgVideo">
    <div class="embed-responsive embed-responsive-16by9">
      <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/rvXubANV7RA" frameborder="0"></iframe>
    </div>
  </div>
</div>

<div class="container fg">
    <div class="row signUpRow">
      <div class="col-sm-6">
        <h2>College</h2>
        <h4>Mondays to Thursdays</h4>
      </div>
      <div class="col-sm-6">
        <h4>Our College Family Groups meet once a week on Drexel, Moore, Penn, Temple, and USciences!</h4>
        <a target="=_blank" href="https://docs.google.com/forms/d/e/1FAIpQLSdxmRfSPxOdAJMTA8wI2DAgvr-Ps2dkyerp_Ud0KJEv7J6V9Q/viewform?embedded=true">Sign up here!</a>
      </div>
    </div>
    <div class="row signUpRow">
      <div class="col-sm-6">
        <h2>Young Adults</h2>
        <h4>Mondays to Thursdays</h4>
      </div>
      <div class="col-sm-6">
        <h4>Our Young Adult Family Groups have a mix of post-undergraduate, grad students, PhD’s, working adults, and young married couples.</h4>
        <a target="_blank" href="https://docs.google.com/forms/d/129Wudp_kpSyppRAM4VFXkJzU0cThdZRfJxkZn1RbkDg/viewform?embedded=true">Sign up here!</a>
      </div>
    </div>
    <div class="row signUpRow">
      <div class="col-sm-6">
        <h2>International Family Group</h2>
        <h4>Thursdays</h4>
      </div>
      <div class="col-sm-6">
        <h4>Description Needed</h4>
        <a href="#">Link Needed</a>
      </div>
    </div>
  </div>
