// client2/app/giving/giving/giving.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'giving',
  templateUrl: './giving.component.html',
  styleUrls: ['./giving.component.css']
})
export class GivingComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="jumbotronMini givingJumbo">
  <h1>Giving</h1>
</div>

<div class="givingDesc">
  <div class="giving container">
    <div class="row">
      <h4>Welcome to GCC’s giving resource!</h4>

      <h4>We would love for you to partner with us
         in the work of raising up kingdom workers who are transformed by Christ to
         influence the world.</h4>
    </div>
  </div>
</div>

<div class="giveWays">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 general">

        <div class="row">
          <h1>General Giving</h1>
        </div>

        <div class="row">
          <h4>Here are three general ways for you to contribute:</h4>
        </div>

        <div class="row ways1">
          <div class="col-sm-4">
            <h4><strong>In Person</strong></h4>
          </div>

          <div class="col-sm-4">
            <h4><strong>By Mail</strong></h4>
          </div>

          <div class="col-sm-4">
            <h4><strong>By Paypal or Credit Card</strong></h4>
          </div>
        </div>

        <div class="row ways2">
          <div class="col-sm-4">
            <h4>During Sunday Service</h4>
          </div>

          <div class="col-sm-4">
            <h4>P.O. Box 13177</h4>
            <h4>Philadelphia PA 19101	</h4>
          </div>

          <div class="col-sm-4">
            <h4>Please see the options below</h4>
          </div>
        </div>

        <div class="row giveNote">
          <h4>Note: Donating via check or cash will save GCC transaction fees.
            Alternatively, if you have a PayPal account, sending money directly
            to <strong>paypal@gracecovenant.net</strong> via the <strong><em>send money to friends and family</em></strong>
            option in PayPal will also save GCC transaction fees.</h4>
        </div>

        <div class="row giveLinks">
          <h4>Those without a PayPal account can donate via credit card below.</h4>
        </div>

        <div class="row oneTimeGive">
          <h4>One time</h4>
          <form action="https://www.paypal.com/cgi-bin/webscr" method="post">
            <input name="cmd" type="hidden" value="_donations">
            <input name="business" type="hidden" value="paypal@gracecovenant.net">
            <input name="item_name" type="hidden" value="GCC Kingdom Vision Fund">
            <input name="no_shipping" type="hidden" value="0">
            <input name="no_note" type="hidden" value="1">
            <input name="currency_code" type="hidden" value="USD">
            <input name="tax" type="hidden" value="0">
            <input name="lc" type="hidden" value="US">
            <input name="bn" type="hidden" value="PP-DonationsBF">
            <input alt="PayPal - The safer, easier way to pay online!" name="submit" src="https://www.paypal.com/en_US/i/btn/btn_donateCC_LG.gif" type="image">
            <img src="https://www.paypal.com/en_US/i/scr/pixel.gif" alt="" border="0"></form>
        </div>

        <div class="row repeatGive">
          <h4>Recurring Donations</h4>
          <form action="https://www.paypal.com/cgi-bin/webscr" method="post">
            <input name="cmd" type="hidden" value="_xclick-subscriptions">
            <input name="business" type="hidden" value="paypal@gracecovenant.net">
            <input name="lc" type="hidden" value="US">
            <input name="item_name" type="hidden" value="GCC Kingdom Vision Fund - Recurring Donation">
            <input name="item_number" type="hidden" value="1234">
            <input name="no_note" type="hidden" value="1">
            <input name="no_shipping" type="hidden" value="0">
            <input name="src" type="hidden" value="1">
            <input name="p3" type="hidden" value="1">
            <input name="currency_code" type="hidden" value="USD">
            <input name="bn" type="hidden" value="PP-SubscriptionsBF:btn_subscribeCC_LG.gif:NonHosted"><p></p>

            <h5>When would you like this to recur?</h5>
            <select name="t3">
              <option value="D">Daily</option>
              <option value="M">Monthly</option>
              <option value="Y">Yearly</option>
            </select>

            <h5>How many times would you like this to recur? (including this payment)</h5>
            <select name="srt">
              <option value="0">Never End</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
              <option value="5">5</option>
              <option value="6">6</option>
              <option value="7">7</option>
              <option value="8">8</option>
              <option value="9">9</option>
              <option value="10">10</option>
              <option value="11">11</option>
              <option value="12">12</option>
            </select>

            <h5>Enter your donation amount:</h5>
            <input maxlength="60" name="a3" type="text">
            <h5><input alt="PayPal - The safer, easier way to<br /> pay online!" name="submit" src="https://www.paypal.com/en_US/i/btn/btn_donateCC_LG.gif" type="image"><br>
            <img src="https://www.paypal.com/en_US/i/scr/pixel.gif" alt="" width="1" height="1" border="0"></h5>
          </form>
        </div>

      </div>
      <div class="col-sm-4">
        <h1>Causes</h1>
        <a class="tile" href="/singapore">
          <div class="singaporeTile">
            <h4>Singapore</h4>
          </div>
        </a>

        <a class="tile" href="/shorttermmissions">
          <div class="missionsTile">
            <h4>Short term Missions</h4>
          </div>
        </a>

        <a class="tile" href="/ministrycenter">
          <div class="ministryCenterTile">
            <h4>Ministry Center</h4>
          </div>
        </a>
      </div>
    </div>
  </div>
</div>

// src/client/pages/Giving.jsx
import React, { Component } from 'react';
import Helmet from 'react-helmet';

import { Form, FormGroup, Label, Col, Input } from 'reactstrap';

import withTitle from '../hoc/withTitle';
import TitleBanner from '../components/TitleBanner';
import contentfulClient from '../modules/contentful';
import TileDeck from '../components/TileDeck';
import Lora from '../components/Lora';

import styles from './Giving.css';

class Giving extends Component {
  constructor(props) {
    super(props);
    this.state = {
      givingList: [],

    };
  }

  componentDidMount() {
    contentfulClient.getEntries({
      content_type: 'giving',
      order: 'fields.name',
    }).then((entries) => {
      const givingList = entries.items.map((item) => {
        const itemName = item.fields.name;
        const imageComponent = (
          <img
            className={styles.image}
            src={item.fields.image.fields.file.url}
            alt={item.fields.image.fields.title}
          />
        );

        const contentComponent = (
          <div>
            <h4><strong>{item.fields.name}</strong></h4>
            <div className={styles.subtitle}><Lora>{item.fields.subtitle}</Lora></div>
            <div className={styles.description}>{item.fields.description}</div>
            {item.fields.link &&
              (
                <a className={styles.link} href={item.fields.link}>
                  <Lora>Learn More ></Lora>
                </a>
               )
            }
          </div>
        );

        return {
          itemName,
          contentComponent,
          imageComponent,
        };
      });

      this.setState({
        givingList,
      });
    });
  }

  render() {
    const { givingList } = this.state;

    return (
      <div id={styles.Giving}>
        <Helmet>
          <link rel="stylesheet" type="text/css" href="/public/assets/pages/Giving.bundle.css" />
        </Helmet>

        <TitleBanner src="/static/images/giving/giving_header.jpg">
          Giving
        </TitleBanner>

        <div className={styles.pageContent}>
          <div className={styles.pageContent}>
            <div className={styles.description}>
              {'Welcome to GCC’s giving resource! We would love for you to partner with us in the work of raising up kingdom workers. Here are three ways in which you can contribute:'}
            </div>

            <div className={styles.description}>
              <h4 className={styles.header}>In Person</h4>
              {'During Sunday Service'}
            </div>

            <div className={styles.description}>
              <h4 className={styles.header}>By Mail</h4>
              {'3700 Baring Street'}<br />
              {'Philadelphia, PA 19104'}
            </div>

            <div className={styles.description}>
              <h4 className={styles.header}>By Paypal or Credit Card</h4>
              {'Donating via check or cash will save GCC transaction fees. Alternatively, if you have a PayPal account, sending money directly to paypal@gracecovenant.net via the “send money to friends and family” option in PayPal will also save us transaction fees. Those without a PayPal account can also donate via credit card below!'}
            </div>

            <div className={styles.donations}>
              <Form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                <h5 className={styles.donationTitle}>Donation Form</h5>
                <input type="hidden" name="cmd" value="_donations" />
                <input type="hidden" name="business" value="paypal@gracecovenant.net" />
                <input type="hidden" name="currency_code" value="USD" />
                <input type="hidden" name="tax" value="0" />
                <input type="hidden" name="lc" value="US" />
                <FormGroup row>
                  <Label className={styles.label} for="item_name" sm={2}>Donation Options</Label>
                  <Col sm={10}>
                    <Input type="select" name="item_name" id="item_name">
                      <option>General Giving</option>
                      { givingList.map(item => (
                        <option>{item.itemName}</option>
                        ))
                      }
                    </Input>
                  </Col>
                </FormGroup>
                <input className={styles.button} type="image" src="https://www.paypalobjects.com/webstatic/en_US/i/buttons/checkout-logo-large.png" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
                <img className={styles.button} alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1" />
              </Form>
            </div>

            <div className={styles.description}>
              <h4 className={styles.header}>Please consider contributing to some of our specific needs.</h4>
              {'If you feel the heart to, you can choose the specific cause/person you’d like to donate to. Whether you’re donating in person, by mail, or sending directly through your PayPal account, please include a note (i.e. “for UC Ministry Center”). Thank you ❤️'}
            </div>

            <TileDeck
              light
              data={givingList}
            />
          </div>
        </div>
      </div>
    );
  }
}

const GivingPage = withTitle('Giving')(Giving);

export default GivingPage;
